export const UserData =[
    {
        Id:'001',
        Name:'Hasnat',
        Email:'hasnatjbajwa@gmail.com',
        Role:'CEO',
        Permissions:'Edit,Modify,Delete,Manage',
    
},
{
    Id:'002',
    Name:'Hasnat',
    Email:'hasnatjbajwa@gmail.com',
    Role:'CEO',
    Permissions:'Edit,Modify,Delete,Manage',
    
},
{
    Id:'003',
    Name:'Hasnat',
    Email:'hasnatjbajwa@gmail.com',
    Role:'CEO',
    Permissions:'Edit,Modify,Delete,Manage',
},
{
    Id:'004',
    Name:'Hasnat',
    Email:'hasnatjbajwa@gmail.com',
    Role:'CEO',
    Permissions:'Edit,Modify,Delete,Manage',
},
{
    Id:'005',
    Name:'Hasnat',
    Email:'hasnatjbajwa@gmail.com',
    Role:'CEO',
    Permissions:'Edit,Modify,Delete,Manage',
}
];